USE comercio;

SELECT NOME, EMAIL, SEXO 
FROM CLIENTE 
ORDER BY NOME;

SELECT NOME, IFNULL(EMAIL, "Sem informação.") SEXO 
FROM CLIENTE 
ORDER BY EMAIL;

SELECT SEXO, COUNT(*) AS GENERO 
FROM CLIENTE 
GROUP BY SEXO 
ORDER BY GENERO DESC; 
