/*
    Função de Agregação (soma): 
    COUNT(*)

    Agrupador: 
    GROUP BY <field>
*/
USE LIVRARIA;
SELECT COUNT(*) AS TOTAL_OF_REGISTERS FROM LIVRO;

SELECT SEX_AUTOR AS GENERO, COUNT(*) FROM LIVRO GROUP BY SEX_AUTOR;

SELECT EDITORA, COUNT(*) FROM LIVRO GROUP BY EDITORA;