CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE LIVRO(
    NOME VARCHAR(100), 
    AUTOR VARCHAR(100), 
    SEX_AUTOR CHAR(1),
    PAGINAS INTEGER, 
    EDITORA VARCHAR(100),
    VALOR DECIMAL(7,2), 
    UF_EDITORA VARCHAR(2),
    ANO_PUBLICACAO VARCHAR(4)  
);

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Cavaleiro Real", "Ana Claudia", "F", 465, "Atlas", 49.90, "RJ", "2009");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("SQL para Leigos", "João Nunes", "M", 450, "Addison", 98.00, "SP", "2018");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Receitas Caseiras", "Celia Tavares", "F", 210, "Atlas", 45.00, "RJ", "2008");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Pessoas Efetivas", "Eduardo Santos", "M", 390, "Beta", 78.99, "RJ", "2018");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Habitos Saudaveis", "Eduardo Santos", "M", 630, "Beta", 150.98, "RJ", "2019");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("A Casa Marrom", "Hermes Macedo", "M", 250, "Bubba", 60.00, "MG", "2016");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Estacio Querido", "Geraldo Francisco", "M", 310, "Insignia", 100.00, "ES", "2015");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Pra Sempre Amigas", "Leda Silva", "F", 510, "Insignia", 78.98, "ES", "2011");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("Copas Inesqueciveis", "Marco Alcantara", "M", 200, "Larson", 130.98, "RS", "2018");

INSERT INTO LIVRO(NOME, AUTOR, SEX_AUTOR, PAGINAS, EDITORA, VALOR, UF_EDITORA, ANO_PUBLICACAO) 
VALUES ("O Poder da Mente", "Clara Mafra", "F", 120, "Continental", 56.58, "RS", "2017");


SELECT NOME, AUTOR, SEX_AUTOR AS GENERO_DO_AUTOR, PAGINAS AS NUMERO_DE_PAGINAS, 
EDITORA, VALOR AS PREÇO_DO_LIVRO, UF_EDITORA, ANO_PUBLICACAO AS ANO_DE_PUBLICAÇÃO 
FROM LIVRO;

SELECT NOME, EDITORA FROM LIVRO;

SELECT NOME, PAGINAS AS NUMERO_DE_PAGINAS FROM LIVRO WHERE SEX_AUTOR = 'F';

SELECT SUM(VALOR) AS SOMA_TOTAL_DOS_LIVROS FROM LIVRO;

SELECT NOME, AUTOR, SEX_AUTOR AS GENERO_AUTOR, UF_EDITORA AS ESTADO FROM LIVRO 
WHERE SEX_AUTOR = 'M' 
AND (UF_EDITORA = "SP"
OR UF_EDITORA = "RJ");

