/*
    SHOW TABLES: SELECT FROM DICIONÁRIO DE DADOS
    SELECT: PROJECTION
    PROJECTION -> SELECT
    SELECTION -> WHERE
*/

SELECT NOW();


SELECT NOME, CPF, SEXO, EMAIL FROM CLIENTE;

/* ALIAS */
SELECT NOME AS CUSTOMER, CPF AS DOCUMENT, EMAIL AS USERNAME FROM CLIENTE;