/*
    DDL: Data Definition Language
    
    ALTER TABLE:
    
    ALTERANDO O NOME DE UMA COLUNA: 
        ALTER TABLE <NOME DA TABELA> 
        CHANGE <NOME ANTIGO DA COLUNA> <NOVO NOME PARA COLUNA> <TIPO> <DEMAIS PARÂMETROS SE HOUVEREM>

    ADICIONANDO UMA NOVA COLUNA: 
        ALTER TABLE <NOME DA TABELA> 
        ADD <NOME DA COLUNA> <TIPO> <DEMAIS PARÂMETROS SE HOUVEREM>
*/