/*
    DDL: Data Definition Language
    
    ALTER TABLE:
    
    ALTERANDO O NOME DE UMA COLUNA: 
        ALTER TABLE <NOME DA TABELA> 
        CHANGE <NOME ANTIGO DA COLUNA> <NOVO NOME PARA COLUNA> <TIPO> <DEMAIS PARÂMETROS SE HOUVEREM>

    ADICIONANDO UMA NOVA COLUNA: 
        ALTER TABLE <NOME DA TABELA> 
        ADD <NOME DA COLUNA> <TIPO> <DEMAIS PARÂMETROS SE HOUVEREM> 
        *Obs: A coluna será acrescida ao final da tabela. É possível insiri-lá no início da tabela com FIRST ou após alguma coluna com AFTER
    

    ADICIONANDO UMA PRIMARY KEY

    ALTER TABLE PRODUCT 
    ADD PRIMARY KEY (NAME);
*/

CREATE DATABASE SOME_DATABASE;
USE SOME_DATABASE;

CREATE TABLE PRODUCT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50), 
    PRICE FLOAT
);

CREATE TABLE CATEGORY(
    ID INT PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL
);

ALTER TABLE PRODUCT 
ADD ID_CATEGORY INT NOT NULL;

ALTER TABLE PRODUCT 
ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (ID_CATEGORY) 
REFERENCES CATEGORY(ID);
