/*
    Exemplo Procedure: 

    1. Modificar o delimiter: 

    CREATE PROCEDURE <NOME DA PROCEDURE>(params type..) 
    BEGIN 
        CORPO DA PROCEDURE; 
    END 
    <CARACTER DO DELIMITER UTILIZADO>

    Apagando uma procedure: 
    DROP PROCEDURE <NOME PROCEDURE>
*/

DELIMITER $

CREATE PROCEDURE SHOW_TIME()
BEGIN 
    SELECT NOW() AS DATE_TIME;
END 
$

DELIMITER $
CREATE PROCEDURE SUM_TWO_VALUES(FVALUE INT, SVALUE INT) 
BEGIN 
    SELECT FVALUE + SVALUE AS TOTAL;
END
$

DELIMITER ;

CALL SHOW_TIME();
DROP PROCEDURE SHOW_TIME;