/*	

Modelagem Conceitual: Rascunho
Modelagem Lógica: Software de Modelagem
Modelagem Física: Script Banco de Dados	

*/


/*
	Cliente 
	Nome - CARACTER(30)
	CPF - NUMERICO(11)
	Email - CARACTER(30)
	Telefone - CARACTER(30)
	Endereço - CARACTER(100)
	Sexo - CARACTER(1)

	Modelagem (brModelo, Astah UML, Workbench)
	Entidade: Tabela
	Atributos: Campos

*/

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE Cliente(
	NOME VARCHAR(30), 
	SEXO CHAR(1), 
	EMAIL VARCHAR(30), 
	CPF VARCHAR(11), 
	TELEFONE VARCHAR(30), 
	ENDERECO VARCHAR(100)
);

SHOW TABLES; 

DESC Cliente;


INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) 
VALUES ('JOAO GABRIEL CARVALHO', 'M', '27.JOAOGABRIEL@GMAIL.COM', 
111111111, '14998045007', 'EDUARDO MARTINS ROMEIRA, RIBEIRÃO DO SUL, SAO PAULO');

INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) 
VALUES ('LAIS MANSANO', 'F', 'LAIS@GMAIL.COM', 
111111111, '14998045007', 'EDUARDO MARTINS ROMEIRA, RIBEIRÃO DO SUL, SAO PAULO');
