/*
    Estrutura: 

    CREATE TRIGGER <NOME>
    BEFORE/AFTER INSERT/DELETE/UPDATE ON <NOME DA TABELA> 
    FOR EACH ROW 
    BEGIN  
        <CORPO DA TRIGGER>
    END
*/

CREATE DATABASE SHOPPING; 
CREATE DATABASE BACKUP_SHOPPING;

USE SHOPPING;

CREATE TABLE PRODUCT(
    ID INT PRIMARY KEY AUTO_INCREMENT, 
    NAME VARCHAR(50) NOT NULL, 
    PRICE FLOAT NOT NULL
); 

USE BACKUP_SHOPPING; 

CREATE TABLE BACKUP_PRODUCT_INSERT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCT INT, 
    NAME VARCHAR(50) NOT NULL, 
    PRICE FLOAT NOT NULL, 
    OCURRENCE DATETIME NOT NULL, 
    BY_USER VARCHAR(100) NOT NULL
); 

CREATE TABLE BACKUP_PRODUCT_DELETE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_PRODUCT INT, 
    NAME VARCHAR(50) NOT NULL, 
    PRICE FLOAT NOT NULL, 
    OCURRENCE DATETIME NOT NULL, 
    BY_USER VARCHAR(100) NOT NULL
);

USE SHOPPING; 

DELIMITER $ 

CREATE TRIGGER BACKUP_PRODUCT_ON_INSERT 
AFTER INSERT ON PRODUCT 
FOR EACH ROW 
BEGIN 
    INSERT INTO BACKUP_SHOPPING.BACKUP_PRODUCT_INSERT(ID_PRODUCT, NAME, PRICE, OCURRENCE, BY_USER) 
    VALUES (NEW.ID, NEW.NAME, NEW.PRICE, NOW(), CURRENT_USER());
END 
$

CREATE TRIGGER BACKUP_PRODUCT_ON_DELETE 
BEFORE DELETE ON PRODUCT 
FOR EACH ROW 
BEGIN 
    INSERT INTO BACKUP_SHOPPING.BACKUP_PRODUCT_DELETE(ID_PRODUCT, NAME, PRICE, OCURRENCE, BY_USER) 
    VALUES (OLD.ID, OLD.NAME, OLD.PRICE, NOW(), CURRENT_USER());
END
$

DELIMITER ;

INSERT INTO PRODUCT(NAME, PRICE) VALUES("Notebook Dell G15", 8.500);
INSERT INTO PRODUCT(NAME, PRICE) VALUES ("Keyboard Redragon", 300);
INSERT INTO PRODUCT(NAME, PRICE) VALUES("Mouse Redragon", 350);
INSERT INTO PRODUCT(NAME, PRICE) VALUES("Test to delete", 100);

DELETE FROM PRODUCT WHERE ID = 4;

SELECT * FROM BACKUP_SHOPPING.BACKUP_PRODUCT_INSERT;
SELECT * FROM BACKUP_SHOPPING.BACKUP_PRODUCT_DELETE;